[[bond]]
source = "tpknam1qr4qkx89nwaanls74ekuentqt4pzefscvzc0v94l43vl4f29gxmuua26fvc"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "107"

[bond.signatures]
tpknam1qr4qkx89nwaanls74ekuentqt4pzefscvzc0v94l43vl4f29gxmuua26fvc = "signam1qqvf3rrqdcv59j56c5rgw3dfm82eypzd6hgq4dqcs096qwy0wv60q9j4k9tyz0qunxmtnn4xlqfd4vr0w2hhmp5e4m74c77vc2u2vngwmz5vq3"


[[bond]]
source = "tpknam1qr4qkx89nwaanls74ekuentqt4pzefscvzc0v94l43vl4f29gxmuua26fvc"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "26"

[bond.signatures]
tpknam1qr4qkx89nwaanls74ekuentqt4pzefscvzc0v94l43vl4f29gxmuua26fvc = "signam1qrzv2j44plexgwmptdxvmtatl0wce736uan7ujgv99mqtsxcu3539z9m2txshl24wtck6y0n0ecp0muqy6p0l80wymfkzlezk9slwrgwfnsdpk"
